### ISSUE TITLE
Negative days: 1 month, -1 day, 3 hours, and 59 minutes

### ISSUE THREAD

**Issue by rfernand** [radar/dotiw#30]
Using distance_of_time_in_words(finish_date, Time.now) dotiw gived as output:
 1 month, -1 day, 3 hours, and 59 minutes

Why the negative days?

**Comment by radar** [comment]
@rfernand is this still an issue? If so, can you please provide steps to reproduce the problem?

**Comment by rfernand** [comment]
Closing this, old issue and don't remember the details anymore.
