### ISSUE TITLE
Deprecation Warning :include_seconds as part of options Hash, not a boolean argument

### ISSUE THREAD

**Issue by canimus** [radar/dotiw#32]
When using the helper function:
```ruby
distance_of_time_in_words Time.now, @test_run.start_time, true, vague:true 
```
A deprecation warning is raised in using Rails 4.0.0 with the following message
DEPRECATION WARNING: distance_of_time_in_words and time_ago_in_words now accept :include_seconds as a part of options hash, not a boolean argument.

**Comment by radar** [comment]
I think this issue is now fixed.
