### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by luisincrespo** [radar/dotiw#45]
Not actually an issue, lack of docs maybe. I just want to know how to use it?. I included the gem in my Gemfile as **gem 'dotiw'**. *distance_of_time_in_words* behaviour still the same.

I'd appreciate any response.

Best.

**Comment by radar** [comment]
Did you restart your server after adding it? It overrides the default.

**Comment by luisincrespo** [comment]
Thanks for your response.

Yep I restarted the server. Still displaying the simple *distance_of_time_in_words*. I'm using foreman for my sever, is there any problem with that?.

**Comment by radar** [comment]
Can you reproduce this issue in a new application?

**Comment by luisincrespo** [comment]
I'll give it a try and let you know!.

**Comment by radar** [comment]
@luisincrespo How did it go?

**Comment by luisincrespo** [comment]
Hey Ryan. Sorry I haven't gotten the time to reproduce the issue in a new
app. I'll be in touch when I do, you can close the issue for now thanks.

**Comment by glampr** [comment]
What is the latest version of this gem pushed to rubygems?
https://rubygems.org/gems/dotiw
This seems quite old... is this the correct one?

**Comment by radar** [comment]
I think you answered your own question.

Please use the version from GitHub until I push a new version.
