### ISSUE TITLE
Spanish locale.

### ISSUE THREAD

**Issue by lurraca** [radar/dotiw#48]
Is there any reason why the spanish locale is not included with the gem as the others [de, en, nb, pl, ru]?

Also the 'es' locale in the spec file have a typo that I would gladly fix. I know that for the purpose of where it's being used doesn't matter (it's just to confirm that the gem would work with custom locales) but if a non-spanish speaker would take it to use in their own application then it's a problem.

**Comment by radar** [comment]
No idea. Probably legacy reasons. If you could submit a PR to move it in there that would be nice.
