### ISSUE TITLE
Unexpected output: "less than 1 second" with only: [:years, :months]

### ISSUE THREAD

**Issue by rvenk** [radar/dotiw#50]
I'm trying to output an age in years and months, but when the output is less than 1 month it outputs "less than 1 second": 
https://github.com/radar/dotiw/blob/master/lib/dotiw/action_view_ext/helpers/date_helper.rb#L61

I think the output should rather be "less than 1 month" or "0 months".

**Comment by radar** [comment]
Please provide exact steps to reproduce this problem.

**Comment by rvenk** [comment]
Quite simple:
```distance_of_time_in_words(Time.now, Time.now, only: [:years, :months])```

**Comment by radar** [comment]
I think this would be a large reworking of how the logic in dotiw works. I do not have the time/energy to do this right now. Can you please investigate a fix for this?

**Comment by rvenk** [comment]
No problem, I'll start working on this later this week.
