### ISSUE TITLE
How to produce rails default distance_of_time_in_words method output

### ISSUE THREAD

**Issue by aman199002** [radar/dotiw#54]
As rails distance_of_time_in_words method has been overridden in this gem. Is it possible to use rails default distance_of_time_in_words with this gem or any other method which produces same output as defined by rails apis.

**Comment by Envek** [comment]
There is [`:vague`](https://github.com/radar/dotiw#vague) option for this, AFAIR. It should be the thing that you need.

**Comment by radar** [comment]
Yes, use the vague option.
