### ISSUE TITLE
dotiw with russian locale doesn't calculate correctly

### ISSUE THREAD

**Issue by advmakerest** [radar/dotiw#55]
So I updated to latest dotiw version (the one on git).

I ran 2 commands in Rails console now check this:

```ruby
>> helper.time_ago_in_words(Time.at(1430356093).utc, :locale => 'en')
"21 days, 12 hours, and 59 minutes"

>> helper.time_ago_in_words(Time.at(1430356093).utc, :locale => 'ru')
"1 день, 12 часов и 59 минут"
```
English version is correct, Russian says "1 day, 12 hours, 59 minutes"

Pretty neat, eyh?

I am running.
ruby 1.9.3p484 (2013-11-22 revision 43786) [x86_64-linux]
Rails 3.2.8

Any suggestions on how to fix is highly appreciated.

**Comment by Envek** [comment]
My blame, sorry. Proposed fix in #56
