### ISSUE TITLE
Mention `old_` prefixed methods in Readme

### ISSUE THREAD

**Issue by esaborit4code** [radar/dotiw#65]
Taking a look to the code in [date_helper.rb#4](https://github.com/radar/dotiw/blob/v3.0.1/lib/dotiw/action_view_ext/helpers/date_helper.rb#L4), my colleague @jguitar realized that the original Rails' methods are aliased with the `old_` prefix, so you can call them that way instead of passing the `vague` option.

It would be nice to mention that in the Readme file as it can be a convenient way to use the original implementation.

**Comment by radar** [comment]
> Says it would be a good idea to mention `old_` methods in the readme

> Doesn't submit a PR for that.

**Comment by radar** [comment]
See the `vague` option, please.

**Comment by esaborit4code** [comment]
> See the `vague` option, please.

As I described above, I suggested this change as an alternative to the `:vague` option.
