### ISSUE TITLE
Russian locales fetch few translation instead of many

### ISSUE THREAD

**Issue by ivanovaleksey** [radar/dotiw#76]
Hi.
I try to use this gem in plain ruby script.
What I do is
```
require 'active_support'
require 'active_support/core_ext'
require 'action_view'
require 'dotiw'
include ActionView::Helpers::DateHelper

distance_of_time_in_words 65.minutes.ago, Time.now, locale: :ru, two_words_connector: ' '
#=> "1 час 5 минуты"
```
But it should be `"1 час 5 минут"`

So it fetched translation for `few` key not for `many`.

Can you please help me to figure it out?

Thank you.

**Comment by ivanovaleksey** [comment]
I figured it out.
I need to put russian plural forms in `config/locale/plurals.rb`

**Comment by M1chael** [comment]
Hi, @ivanovaleksey!
Can you please explain, how to fix this issue? I can't even find `config/locale/plurals.rb`.

**Comment by ivanovaleksey** [comment]
@M1chael it was a long ago :)
I have found that project, it is just Ruby script, not Rails application. Though the following gems are used for translation helpers.
```
gem 'activesupport'
gem 'actionview'
gem 'russian'
gem 'dotiw'
```
The project doesn't contain `config/locale/plurals.rb` too. As far as I understand it is kind of a file that I18n library can automatically look for. You can try to google to find out more about it https://stackoverflow.com/a/6166091/3475678.

I guess maybe it is the `russian` gem that does the trick. In the OP I didn't have the gem but now it is added in the project.
The gem does define plurals for Russian language https://github.com/yaroslav/russian/blob/master/lib/russian/locale/pluralization.rb

You could try to require the gems from OP + `russian` and play in REPL

**Comment by M1chael** [comment]
Thanks a lot!

It works for me in this way without rails:
```
I18n.load_path += Dir['/path/to/plurals.rb']
I18n.backend.load_translations
I18n::Backend::Simple.send(:include, I18n::Backend::Pluralization)
```
[plurals.rb](https://raw.githubusercontent.com/ruby-i18n/i18n/master/test/test_data/locales/plurals.rb) I take from your link to SO question.
